# Columns in the final table, mapping of keys to column names, double underscores refers to nests.
COLUMNS:
  key: Name
  office_location: Location
  glassdoor__rating: Glassdoor rating
  office_picture: Office Picture XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  software_engineer__salary: Mid-Level Engineer Salary
  software_engineer__bonus: Bonus
  software_engineer__stock_options: Stock Options
  pantry: Pantry
  annual_leaves: Annual Leaves
  glassdoor__company_size: Company size
  glassdoor__company_revenue: Company revenue
  benefits: Insurance XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  flexible_hours: Flexible hours
  notes: Notes


#% Companies

Agoda:
  career_page: https://careersatagoda.com
  office_location: Tanjong Pagar
  office_picture: pictures/agoda.jpeg
  glassdoor:
    link:
    # Overwrites
    rating: 3.9
    company_size: 10001 to 50000
    company_revenue: $100M-$500M
  software_engineer:
    link:
    # Overwrites
    salary: $7000
    bonus: Yes
    stock_options: Yes
  pantry: 8/10
  annual_leaves: 18
  flexible_hours: Yes
  benefits:
    good_insurance: Yes
    pregnancy: Yes
    maternity_leaves: 4
    covers_dependents: Yes
    extras: But dependents costs $109/month to be covered
  notes: ''
  strike_out: no

Carousell:
  career_page: https://careers.carousell.com/
  office_location: Tanjong Pagar
  office_picture: pictures/carousell.jpeg
  glassdoor:
    link:
    # Overwrites
    rating: 3.3
    company_size: 201 to 500
    company_revenue: unknown
  software_engineer:
    link:
    # Overwrites
    salary: $6000-7000
    bonus: No
    stock_options: Yes
  pantry: basic
  annual_leaves: 14
  flexible_hours: Yes
  benefits:
    good_insurance: No
    pregnancy: No
    maternity_leaves: 4
    covers_dependents: No
    extras:
  notes: ''
  strike_out: yes





### List of companies
#| Name | Location | Glassdoor Rating | Office Picture AAAAAAAAAAAAAAAAAAAAAAA | Mid Level Engineer Salary | Bonus | Stock Options | Pantry | Annual Leaves | Size | Revenue | Insurance for dependents, Covers pregnancy? | Notes |
#|---|---|---|---|---|---|---|---|---|---|---|---|---|
#| [Agoda](https://careersatagoda.com/)  | Tanjong Pagar | 3.9 | <img src="pictures/agoda.jpeg" alt="Agoda Office" height="250" width="400" > | $7000 | Yes | Yes | 8/10 | 18 | 1001 to 5000 | $100M-$500M | No/Pay $109 for dependents, No |
#| [Carousell](https://careers.carousell.com/) | Tanjong Pagar | 3.3 | <img src="pictures/carousell.jpeg" alt="Carousell Office" height="250" width="400" > | $6000-$7000 | No | Yes | ? | 14 | 201 to 500 | N/A | No, No |~~
#| [DRW](https://drw.com/careers/) | Downtown/Marina Bay | 4.2 | <img src="pictures/drw.jpg" alt="Drw Office" height="250" width="400" > | $8000->$10k++) | Yes!$$ | No | Good | 18-25(Depending on length of service) | 1001 to 5000 | Unknown | Yes, Yes | Daily Catered Breakfasts, includes retirement plan |
#| [Facebook](https://www.facebook.com/careers/) | Marina One | 4.3 | <img src="pictures/facebook.jpg" alt="Facebook Office" height="250" width="400" > | $8000-$9000 | Yes$$ | Yes$$ | Good | 21 | 10k+| $10B+ | Yes, Yes, dental, vision, TCM, you name it |  Signing bonus, Flexible to choose own work hours, Free Meals 3 times a day. 4 months maternity. Paid vacations.
#
#
#| [Go-Jek](https://www.gojek.io/careers/) | Tanjong Pagar | Summer | No intern positions listed |
#| [Google](https://careers.google.com/jobs/results/142027906936120006-software-engineering-intern-summer-2020/?company=Google&company=YouTube&hl=en&jlo=en-US&location=Singapore&q=Software%20Engineering%20intern)  | Pasir Panjang | Summer | Deadline: 31st October 2019 | Within 12-18 months of completing a Bachelor's or Master's degree
#| [Google (STEP)](https://careers.google.com/jobs/results/97828209514422982-student-training-in-engineering-program-step-intern-2020/?company=Google&company=YouTube&hl=en&jlo=en-US&location=Singapore&q=Software%20Engineering%20intern)  | Pasir Panjang | Summer | Deadline: 31st October 2019 |
#| [GovTech](https://govtech.taleo.net/careersection/govtech_internship/jobsearch.ftl)| Depends on team| Summer| |
#| [Grab](https://grab.careers/job-details/?id=962b081ccd05013e0a432d0006525ea0)  | Marina One | Unknown | Data Analytics & Data Science, ATAP |
#| [Honestbee](https://careers.honestbee.com/departments/job/)  | Tiong Bahru | Summer | No intern positions listed |
#| [HopeTechnik](https://www.hopetechnik.com/careers/) | Jurong | All-year around| Software Engineering Intern && Technical Analyst && Mechanical Engineering Intern |
#|IBM | Changi Business Park | Unknown | |
#| [JPMorgan](https://jpmchase.taleo.net/careersection/10140/jobdetail.ftl?job=190064684)| | Summer|October 27, 2019|
#| [Jump Trading](https://www.jumptrading.com/jobs.html)  | Downtown | Summer | |
#| [Lazada](http://www.lazada.com/work-at-lazada) | Tanjong Pagar | Summer | |
#| [Nutonomy](https://www.nutonomy.com/careers/) | Jurong | All-year-around | Autonomous Driving Intern. Note that you need to be on a MS/PhD track |
#| [OpenGovProducts](https://opengovernmentproducts.recruitee.com/)| Funan| All-year-round| SE & UX interns; Only Singaporean or PR allowed;|
#| [SEA(Garena)](https://career.seagroup.com/programs?pos=LIP-area)  | One-North | All-year around | |
#| [ShopBack](http://careers.shopback.com/singapore)  | One-North | Summer | No SE intern positions listed |
#| [SEA(Shopee)](https://careers.shopee.sg/) | Kent-Ridge | All-year around | |
#| [Stripe](https://stripe.com/jobs/listing/software-engineering-intern-apac/1806024?gh_src=73vnei) | Outram Park | Summer | |
#| Traveloka| Unknown | Summer | |
#| Twitter  | Raffles Place/Downtown | Summer | |
#| [VISA](https://jobs.smartrecruiters.com/oneclick-ui/company/108611351/job/1520850202/publication/743999693253063)  | Paya Lebar | Summer | Might include an all-paid trip to the VISA HQ in San Francisco |
#| [ViSenze](https://visenze.workable.com/jobs/708797/candidates/new)  | One-North | Unknown | |
#| Yitu Tech | Pasir Panjang | Summer/Winter | |
#| [Zendesk](https://www.zendesk.com/jobs/singapore/)  | Commonwealth | Summer | No intern positions listed |
