
| [Go-Jek](https://www.gojek.io/careers/) | Tanjong Pagar | Summer | No intern positions listed |
| [Google](https://careers.google.com/jobs/results/142027906936120006-software-engineering-intern-summer-2020/?company=Google&company=YouTube&hl=en&jlo=en-US&location=Singapore&q=Software%20Engineering%20intern)  | Pasir Panjang | Summer | Deadline: 31st October 2019 | Within 12-18 months of completing a Bachelor's or Master's degree
| [Google (STEP)](https://careers.google.com/jobs/results/97828209514422982-student-training-in-engineering-program-step-intern-2020/?company=Google&company=YouTube&hl=en&jlo=en-US&location=Singapore&q=Software%20Engineering%20intern)  | Pasir Panjang | Summer | Deadline: 31st October 2019 |
| [GovTech](https://govtech.taleo.net/careersection/govtech_internship/jobsearch.ftl)| Depends on team| Summer| |
| [Grab](https://grab.careers/job-details/?id=962b081ccd05013e0a432d0006525ea0)  | Marina One | Unknown | Data Analytics & Data Science, ATAP |
| [Honestbee](https://careers.honestbee.com/departments/job/)  | Tiong Bahru | Summer | No intern positions listed |
| [HopeTechnik](https://www.hopetechnik.com/careers/) | Jurong | All-year around| Software Engineering Intern && Technical Analyst && Mechanical Engineering Intern |
|IBM | Changi Business Park | Unknown | |
| [JPMorgan](https://jpmchase.taleo.net/careersection/10140/jobdetail.ftl?job=190064684)| | Summer|October 27, 2019|
| [Jump Trading](https://www.jumptrading.com/jobs.html)  | Downtown | Summer | |
| [Lazada](http://www.lazada.com/work-at-lazada) | Tanjong Pagar | Summer | |
| [Nutonomy](https://www.nutonomy.com/careers/) | Jurong | All-year-around | Autonomous Driving Intern. Note that you need to be on a MS/PhD track |
| [OpenGovProducts](https://opengovernmentproducts.recruitee.com/)| Funan| All-year-round| SE & UX interns; Only Singaporean or PR allowed;|
| [SEA(Garena)](https://career.seagroup.com/programs?pos=LIP-area)  | One-North | All-year around | |
| [ShopBack](http://careers.shopback.com/singapore)  | One-North | Summer | No SE intern positions listed |
| [SEA(Shopee)](https://careers.shopee.sg/) | Kent-Ridge | All-year around | |
| [Stripe](https://stripe.com/jobs/listing/software-engineering-intern-apac/1806024?gh_src=73vnei) | Outram Park | Summer | |
| Traveloka| Unknown | Summer | |
| Twitter  | Raffles Place/Downtown | Summer | |
| [VISA](https://jobs.smartrecruiters.com/oneclick-ui/company/108611351/job/1520850202/publication/743999693253063)  | Paya Lebar | Summer | Might include an all-paid trip to the VISA HQ in San Francisco |
| [ViSenze](https://visenze.workable.com/jobs/708797/candidates/new)  | One-North | Unknown | |
| Yitu Tech | Pasir Panjang | Summer/Winter | |
| [Zendesk](https://www.zendesk.com/jobs/singapore/)  | Commonwealth | Summer | No intern positions listed |
